### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by loganator956** [Xenorenaus/CMP1903M-Assessment-1#10]
I think that on `Analyse.cs`, it could be helpful to add comments clearly stating what you're counting in each statistic section. 
Error handling works well, although you have suppressed the `CS8600` error where you `Console.ReadLine()` could return null rather than checking the return value of it. 
Furthermore, comments on what some lines are doing can help other people more quickly understand what the code is doing.

**Comment by Xenorenaus** [comment]
Which values are tracked where are stated at the beginning of the AnalyseText method

IncrementValuesList method renamed AddToFileOutputStrings
-Description comment changed to be more appropriate

More comments added to clarity

Errors no longer suppressed, default to "";
