### ISSUE TITLE
Handling of Optional Variables

### ISSUE THREAD

**Issue by kit-calloway** [Xenorenaus/CMP1903M-Assessment-1#9]
Noticed that your code uses some obscure method to disable errors pertaining to assigning optional type values (e.g. `Console.ReadLine()`) to non-optional variables.

Would recommend use of the `??` operator instead (e.g. `input = Console.ReadLine() ?? "";`).

If you're unfamiliar with the syntax, `""` is returned should `Console.ReadLine()` ever return null.

**Comment by Xenorenaus** [comment]
Thank you for this, had no idea it was possible.
Changed this and removed ignoring warnings
